---
title: "Assignment 1"
---

My first assignment has two parts.

## (a) "**Veri Bilimi ve Endüstri Mühendisliği Üzerine Sohbetler - Mustafa Baydoğan & Erdi Daşdemir"**

Associate Professor Dr. Mustafa Baydoğan, in his webinar video titled **"Data-Driven Decision Making,"** provided an explanation of the use of data and analytical methods in decision-making processes. He shared examples based on his experiences on how machine learning and deep learning techniques can be applied in prediction and optimization processes. The knowledge and expertise of industrial engineers give them a competitive edge in machine learning-based optimization studies. The topic of **optimization with machine learning** is truly inspiring.

## (b) Analysis of "mtcars" Dataset

```{r}
compute_stats <- function(x) {
  return(c(
    mean = mean(x),
    median = median(x),
    variance = var(x),
    IQR = IQR(x),
    min = min(x),
    max = max(x)
  ))
}


data(mtcars)

for (i in names(mtcars)) {
  stats <- compute_stats(mtcars[[i]])
  cat("\nColumn: ", i, "\n")
  print(stats)
  cat("\n-------------------\n")
}


result_sapply <- sapply(mtcars, compute_stats)
print(result_sapply)


result_apply <- apply(mtcars, 2, compute_stats)
print(result_apply)


library(dslabs)
data(na_example)
print(na_example)


na_count <- sum(is.na(na_example))
cat("\n Number of NA:", na_count, "\n")

na_positions <- which(is.na(na_example))
cat("Index of NA:", na_positions, "\n")


mean_without_na <- mean(na_example, na.rm = TRUE)
sd_without_na <- sd(na_example, na.rm = TRUE)


median_value <- median(na_example, na.rm = TRUE)
na_example_median <- na_example
na_example_median[is.na(na_example_median)] <- median_value
mean_median_replacement <- mean(na_example_median)
sd_median_replacement <- sd(na_example_median)


valid_values <- na_example[!is.na(na_example)]

na_example_random <- na_example
na_example_random[is.na(na_example_random)] <- sample(valid_values, sum(is.na(na_example_random)), replace = TRUE)

mean_na_random <- mean(na_example_random)
sd_na_random <- sd(na_example_random)


comparison_table <- data.frame(
  Method = c("Without NA", "Median Replacement", "Random Replacement"),
  Mean = c(mean_without_na, mean_median_replacement, mean_na_random),
  SD = c(sd_without_na, sd_median_replacement, sd_na_random)
)

print(comparison_table)
```

The random data selection method is more appropriate. The results obtained in the step where we replaced the NA values using random data selection are very close to those obtained with the original dataset. This can be observed when we examine the mean and standard deviation values. However, in the step where we replaced data using the median, both the mean and standard deviation have decreased. Replacing 145 NA values with the median has altered the distribution of the data.
